name: Main_Workflows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building"

  test2:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests.."